const fs = require("fs");
const r = fs.readFileSync(0, "utf8");
let line = r.split(" ");
let a = parseFloat(line[0]);
let b = parseFloat(line[1]);
let c = parseFloat(line[2]);
console.log(`TRIANGULO: ${(a*c/2).toFixed(3)}`);
console.log(`CIRCULO: ${(3.14159*c*c).toFixed(3)}`);
console.log(`TRAPEZIO: ${((a+b)*c/2).toFixed(3)}`);
console.log(`QUADRADO: ${(b*b).toFixed(3)}`);
console.log(`RETANGULO: ${(a*b).toFixed(3)}`);